.github/workflows/pr_tests.yml
.gitmodules
Makefile
README.md
include/correction.h
src/correction.cc
src/demo.cc

Following https://github.com/nsmith-/correctionlib/discussions/17#discussioncomment-315714

Implement formula evaluator

---

data/conversion.py
data/schemav2.json
include/correction.h
src/correction.cc
src/correctionlib/convert.py
src/correctionlib/schemav2.py
tests/test_core.py

All nodes requiring input now specify the variable name

---

data/conversion.py
data/schemav2.json
include/correction.h
src/correction.cc
src/correctionlib/convert.py
src/correctionlib/schemav2.py
tests/test_core.py

`Binning` and `MultiBinning` now have `flow: Union[Content, Literal["clamp", "error"]]` attributes. Currently set mandatory.
Closes #5

Add overflow behavior handling in binning nodes

---

include/correction.h
src/correction.cc
src/correctionlib/schemav2.py
tests/test_core.py

Closes #1
Also clean up handling of optional attributes in evaluator

Add optional default to Category node

---

include/correction.h
src/correction.cc
src/demo.cc

One due to an expensive allocation (seen in profiler)
The other due to an unproven suspicion that small `sizeof(Content)` is better (more nodes can stay in cache)

A few optimizations

---

src/correctionlib/JSONEncoder.py
tests/test_jsonencoder.py

Fixes small bug in the JSON encoder from #57:
* divide elements evenly over multiple lines (bug affected an edge case)
* added check in test script to ensure data can be loaded and is unchanged before/after encoding
This is to replace https://github.com/cms-nanoAOD/correctionlib/pull/63, because I don't know what squashing merges means.

Fix small bug in JSON encoder

---

src/correction.cc
tests/test_core.py

Per rapidjson docs: 
> Allow parsing NaN, Inf, Infinity, -Inf and -Infinity as double values (relaxed JSON syntax).

Support NaN/inf JSON extensions

---

src/correctionlib/cli.py

Only the "corrections" property of CorrectionSets was merged before, resulting in inconsistent merged JSON files, when CompoundCorrection is used in source JSONs.

(CLI): include compound corrections in merge

---

.github/workflows/ci.yml
src/correctionlib/convert.py
src/correctionlib/schemav2.py

`convert.from_uproot_THx` did not work with uproot 4.2.0 because of the `TAxis` behaviour: the elements obtained when iterating on an axis are not tuples but numpy arrays. Simply removing the `isinstance` assertion makes it work fine.
I've also added the possibility to specify the axis names and flow in `from_uproot_THx` and `from_histogram`, to make those slightly more useful,

Convert from uproot: fix bug, specify axis names and flow

---

src/correctionlib/highlevel.py

Allows use of (flat) awkward arrays without the annoying `np.array()` wrap everywhere.
Still need to make it work for jagged awkward arrays (#125)

Allow numpy-like arrays in highlevel

---

src/correctionlib/convert.py

The definition of the axes types for histogram conversion were not the expected ones ("string", "int", "real"). 
For example, with the proposed changes the  histogram below got converted correctly. 
```
(StrCategory([...], growth=True, name='Sample', label='Sample'),
StrCategory([...], growth=True, name='Year', label='Year'),
Variable([4, 5, 6, 7, 8, 9, 17], name='Njet', label='N Jets'),
Variable([0, 500, 750, 1000, 1250, 1500, 2000], name='Ht', label='$H_T$ Jets'))
```

Correcting axes types for histogram conversion

---

.github/workflows/ci.yml
.pre-commit-config.yaml
setup.cfg
src/correctionlib/cli.py

Just for the CI for now, as github runners no longer provide it. The code should still be compatible.

Drop python 3.6

---

include/correction.h
src/correction.cc
src/correctionlib/schemav2.py
tests/test_core.py

When defining a Binning, the `edges` attribute can now be either a list of floats (like before) or an instance of UniformBinning(n, low, high). When using the latter option, the Binning correction is optimized to use a simple arithmetic formula rather than binary search to look up the bin index.
This is a fresh (better) take on #181 .
Example usage:
```python
from correctionlib import schemav2 as schema
if __name__ == "__main__":
corr = schema.Correction(
name="test",
version=2,
inputs=[schema.Variable(name="x", type="real")],
output=schema.Variable(name="a scale", type="real"),
data=schema.Binning(
nodetype="binning",
input="x",
edges=schema.UniformBinning(n=2, low=0., high=2.),
content=[1.0, 2.0],
flow="error",
),
)
e = corr.to_evaluator()
print(e.evaluate(0.5))
print(e.evaluate(1.0)) …
```

Add UniformBinning to schemav2

---

pyproject.toml

1. make on PyPI does not provide access to make build tool
2. wheel dependency is declared by setuptools automatically
To clarify the second point, PEP 517 provides [a way](https://peps.python.org/pep-0517/#get-requires-for-build-wheel) for build backends like setuptools to express additional dependencies that they need for either building a wheel or an sdist. If we let setuptools do this for us, `wheel` will only be included as a dependency when building wheels and not an sdist.
My motivation is from working on migrating Python packages in [nixpkgs](https://github.com/NixOS/nixpkgs) to use [`build`](https://pypa-build.readthedocs.io/en/latest/), which validates that all the build dependencies declared are present, and I do not want to package [make](https://pypi.org/project/make/).

Remove some unneeded build dependencies.

---

setup.cfg

This is a hard requirement of awkward, which is required for tests, but it was not a requirement in general, so was not caught in CI.

Add packaging requirement

---

include/correction.h
src/formula_ast.cc

Before this commit, for some binary and unary operations FormulaAST was storing opaque function pointers,
losing the information about what the operation was. Now we always store the kind of operation as part
of the AST node.
This patch also makes treatment of different kinds of unary and binary operations more uniform and,
during AST evaluation, removes the indirection
due to calling code through the function pointer.

Store all information about the AST in FormulaAST

---

include/correction.h
src/correction.cc

Before this commit, most correction types implemented an `evaluate` method while some implemented a `child` method. When walking a correction's compute graph, the `node_evaluate` visitor had to know which ones required recursive visiting and which did not.
With this patch, all correction types implement `evaluate`. This simplifies the implementation of the `node_evaluate` visitor considerably and keeps the logic related to the handling of each type of correction local to the corrections themselves.
@nsmith- just an idea, feel free to close if you don't like the direction.

Make interfaces of C++ correction types more uniform

---

setup.cfg
src/correctionlib/highlevel.py
tests/test_highlevel.py

Also add awkward wrapper to CompoundCorrection.
This PR lets us pass dask_awkward.Array into correctionlib corrections.
It does the wrapping of the correction into a delayed object and map_partitions call internally now.
```python3
evaluate = sf.evaluate(
dx,
1.0,
)
```
Is significantly cleaner than the `map_partitions` version.

feat: add dask_awkward wrapper to Correction and CompoundCorrection

---

src/correctionlib/__init__.py
src/correctionlib/binding.py
src/correctionlib/cli.py
src/correctionlib/util.py

I followed the migration guide:
https://importlib-resources.readthedocs.io/en/latest/migration.html.
Unfortunately the new APIs are only available as of Python 3.9. There are other ones, also in `importlib.resources`, that are available since 3.7 but are deprecated and 3.11.
As a rationale for the migration, see https://github.com/cms-nanoAOD/correctionlib/issues/211.

Move away from deprecated pkg_resources

---

.github/workflows/ci.yml
.pre-commit-config.yaml
src/correctionlib/JSONEncoder.py
src/correctionlib/binding.py
tests/test_binding.py
tests/test_core_valid.py

ROOT can't accept the pathlib paths that were introduced in #210 
Fix: cast to `str` and test!

Fix PyROOT binding registration

---

.github/workflows/ci.yml
src/correction.cc
src/correctionlib/schemav2.py
tests/test_core.py
tests/test_issue208.py

pybind11 upgrade fixes #240 and string infinity fixes #208 (or rather, the issue with newer pydantic versions)

Update to pybind11 v2.12 and migrate to string infinity

---

src/correction.cc

This is so the evaluator can continue to read json produced pre-v2.6 The schema validator will continue to test for float infinity and warn to migrate to string infinity.
The alternative would be to migrate all json to string infinity, but that would not be readable by older evaluators, which is more of a usability issue than the lack of standards-compliance in old json files, for now.
Closes #247

Re-enable rapidjson::kParseNanAndInfFlag for backwards-compatibility

---

src/correctionlib/cli.py

On invocation without any argument we now get:
```
usage: correction [-h] [--width WIDTH] [--html HTML] {validate,summary,merge,config} ...
Command-line interface to correctionlib.
positional arguments:
{validate,summary,merge,config}
validate            Check if all files are valid
summary             Print a summmary of the corrections
merge               Merge one or more correction files and print to stdout
config              Configuration and linking information
options:
-h, --help            show this help message and exit
--width WIDTH         Rich output width
--html HTML           Save terminal output to an HTML file
Subcommand usage (specify -h for more detail):
usage: correction validate [-h] [--quiet] [--failfast] [--version VERSION] [--ignore-float-inf] FILE [FILE ...] …
```

Make the help message slightly more clear

---

src/correctionlib/schemav2.py

To fix:
src/correctionlib/schemav2.py:419:37: B910 Use Counter() instead of defaultdict(int) to avoid excessive memory use

Migrate from defaultdict to Counter

---

.github/workflows/ci.yml
.github/workflows/wheels.yml
setup.cfg

An implicit request for coffea 0.7 container building.
@oshadura

build: add aarch64 wheels and upkeep chores

---

.github/workflows/ci.yml
tests/test_binding.py

Let's try fixing https://github.com/cms-nanoAOD/correctionlib/pull/279#issuecomment-2682478360.

Try fetching tags to get correct version in CI

---

pyproject.toml
src/correctionlib/cli.py

Add "--ignore-float-inf" for the CLI, when running "correction summary".
Follow-up of: https://gitlab.cern.ch/cms-nanoAOD/jsonpog-integration/-/merge_requests/99

Add "--ignore-float-inf" for "correction summary"
