cms-nanoAOD/correctionlib

correctionlib/schemav1.py, requirements.txt
=> Python 3.6+ compatibility

Makefile, include/correction.h, setup.py, src/correction.cc, src/correctionlib/schemav2.py, src/demo.cc, src/formula_ast.cc, tests/test_core.py
=> FormulaRef

include/correction.h, src/correction.cc, src/correctionlib/schemav2.py, tests/test_core.py
For better or worse. Closes #3
Also fixes a bug in Category, turns out order of union is important!
=> Implement a Transform node

tests/test_core.py
Manual run was successful: https://github.com/nsmith-/correctionlib/actions/runs/662018147
=> Drop i686 tests

src/correctionlib/schemav2.py, tests/test_issue058.py
Closes #58
Also add some validation for Category
=> Enforce strict types in CategoryItem

src/correction.cc, src/correctionlib/_core/__init__.pyi, src/correctionlib/highlevel.py, src/python.cc, tests/test_core_vect.py, tests/test_highlevel.py
=> Vectorized evaluation

src/correctionlib/highlevel.py, tests/test_highlevel.py
=> Make highlevel correction objects pickleable

include/correction.h, src/correction.cc, src/correctionlib/cli.py, src/correctionlib/schemav2.py, src/python.cc, tests/test_core.py
=> Add optional CorrectionSet description string

.gitmodules
=> Update cpp-peglib url

src/correction.cc
=> Raise an error for bad paths

README.md
=> Add conda badge

Makefile, docs/install.md
This is to support https://github.com/cms-sw/cmsdist/pull/7523
I don't think we need a new release, just to remember to switch the branch in cmsdist next time
=> Revise Makefile for cmssw externals

.github/workflows/wheels.yml, pyproject.toml, src/correctionlib/highlevel.py, src/correctionlib/schemav2.py
Also some small patches to expose variables
=> Get wheels working again

pyproject.toml
Hopefully to fix https://github.com/conda-forge/correctionlib-feedstock/pull/9
=> Upgrade pybind11 to v2.10.0

src/python.cc
For the scalar `eval` I think I'll leave it alone, probably too short to be worth release and acquire
=> Release GIL in veval

.github/workflows/ci.yml, .github/workflows/wheels.yml, .pre-commit-config.yaml, pyproject.toml, setup.cfg, src/correctionlib/JSONEncoder.py, src/correctionlib/schemav1.py, src/correctionlib/schemav2.py
Will need to handle pydantic 2 at some point soon.
=> CI maintenance

.pre-commit-config.yaml, data/conversion.py, setup.cfg, src/correction.cc, src/correctionlib/JSONEncoder.py, src/correctionlib/cli.py, src/correctionlib/convert.py, src/correctionlib/highlevel.py, src/correctionlib/schemav1.py, src/correctionlib/schemav2.py, tests/test_compound.py, tests/test_core.py, tests/test_core_valid.py, tests/test_core_vect.py, tests/test_formula_ast.py, tests/test_hashprng.py, tests/test_highlevel.py, tests/test_unique.py
Trying first to just bump the version.
=> Migrate to pydantic2

src/correctionlib/schemav2.py
=> Better error for missing input

src/correction.cc
=> Duplicate check in evaluator

src/correction.cc, tests/test_issue217.py
=> Cast int inputs to double in binning evaluations

src/correctionlib/cli.py
=> Use fast printing for pydantic validation errors

src/correctionlib/cli.py, src/correctionlib/schemav2.py
=> Add a validation option to ignore float infinities in bin edges

src/correctionlib/schemav2.py
Fixes https://github.com/cms-nanoAOD/correctionlib/issues/45 and supersedes #124
=> Use discriminated union for nodetype

.github/workflows/wheels.yml
=> fix: move to 12 Mar 2025 rapidjson master

.github/workflows/wheels.yml
Much more efficient than qemu.
=> ci: use new native arm builders for wheels

.pre-commit-config.yaml, pyproject.toml, src/correctionlib/schemav1.py, src/correctionlib/schemav2.py, src/correctionlib/util.py
=> build: update to pybind11 3, modernize python

src/correctionlib/util.py
this didn't make it in, and it is much more clear / robust.
=> fix: better implementation of this_module_path
